name:                HaskellExercises
version:             0.1.0.0
github:              "daniel-chambers/HaskellExercises"
license:             BSD3
author:              "Daniel Chambers"
maintainer:          "daniel@digitallycreated.net"
copyright:           "2019 Daniel Chambers"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/daniel-chambers/HaskellExercises#readme>

default-extensions:
- DerivingStrategies

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  HaskellExercises-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellExercises

tests:
  HaskellExercises-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellExercises
    - hspec
